name: ninjachiken
description: "Ninja Chiken Game"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  audioplayers: ^6.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/iconapp.png"
  min_sdk_android: 21

flutter: 
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
