// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNtGfReyntl25HwxLoFNVhMWYwwZADHEc',
    appId: '1:965580926816:android:77e4c9c35cfc585d767805',
    messagingSenderId: '965580926816',
    projectId: 'ninjachiken-b151d',
    storageBucket: 'ninjachiken-b151d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRXuVWPxmqT8Yn-mDHq1m3QMPW9rwTFag',
    appId: '1:965580926816:ios:9e5a9e954176efe1767805',
    messagingSenderId: '965580926816',
    projectId: 'ninjachiken-b151d',
    storageBucket: 'ninjachiken-b151d.firebasestorage.app',
    iosBundleId: 'com.ninjachicken.eggroad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPDtJwZ-OwKatc2J0FrdcQC3b2TpEUfGs',
    appId: '1:965580926816:web:37026ab3d13ac344767805',
    messagingSenderId: '965580926816',
    projectId: 'ninjachiken-b151d',
    authDomain: 'ninjachiken-b151d.firebaseapp.com',
    storageBucket: 'ninjachiken-b151d.firebasestorage.app',
    measurementId: 'G-D8GHE3PCJ8',
  );
}
